container:
  image: node:latest
check_task:
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install
  osx_instance:
    image: high-sierra-xcode-9.4
  script: 
    - yarn run build 
    - npm run package-mac