container:
  image: circleci/node@sha256:895bd70ebcf4fd8a61a38f236fdea711859ac5d24357dc419559e53b06bac476
check_task:
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install
  osx_instance:
    image: high-sierra-xcode-9.4
  script: 
    - yarn run build 
    - yarn run package-mac