matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: "10"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
    - os: windows
      language: node_js
      node_js: "10"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - YARN_GPG=no
cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.cache/yarn

before_install:
  - |
    if ["$TRAVIS_OS_NAME" == "windows"]; then
      export NODEPATH=$(where.exe node.exe)
      export PROJECTDIR=$(pwd)
      export YARNCACHE=$(yarn cache dir)
      export TEMPDIR=$LOCALAPPDATA\\Temp

      powershell Add-MpPreference -ExclusionProcess ${NODEPATH}
      powershell Add-MpPreference -ExclusionPath ${YARNCACHE}
      powershell Add-MpPreference -ExclusionPath ${PROJECTDIR}
      powershell Add-MpPreference -ExclusionPath ${TEMPDIR}

      echo "DisableArchiveScanning..."
      powershell Start-Process -PassThru -Wait PowerShell -ArgumentList "'-Command Set-MpPreference -DisableArchiveScanning \$true'"

      echo "DisableBehaviorMonitoring..."
      powershell Start-Process -PassThru -Wait PowerShell -ArgumentList "'-Command Set-MpPreference -DisableBehaviorMonitoring \$true'"

      echo "DisableRealtimeMonitoring..."
      powershell Start-Process -PassThru -Wait PowerShell -ArgumentList "'-Command Set-MpPreference -DisableRealtimeMonitoring \$true'"
    fi
    yarn install --network-timeout 1000000
    
script: 
  - |
    if [ "$TRAVIS_OS_NAME" == "windows" ]; then
      yarn dist-win
    else
      yarn dist-mac
    fi

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
