matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: "10"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.cache/yarn

script: yarn install && yarn run build && yarn package-mac

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
