matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: "10"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
    - os: windows
      language: node_js
      node_js: "10"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.cache/yarn

script: 
  - |
    if [ "$TRAVIS_OS_NAME" == "windows" ]; then
      yarn install && yarn run build && yarn package-win
    else
      yarn install && yarn run build && yarn package-mac
    fi

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
