name: Github CI

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build-mac:
    name: "MacOS build"
    runs-on: macOS-10.14    
    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      run: |
        yarn install
        yarn dist-mac
  
  build-win:
    name: "Windows build"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run build script (windows)
        run: |
          yarn install
          yarn dist-win
    
